const $=(s)=>document.querySelector(s);
const businesses={
 cafe:{name:'MAISON CAFÉ',image:'cafe',alt:'Brunch et café, illustration de concept',eyebrow:'CAFÉ · CONCEPT DE DÉMONSTRATION',title:'Votre prochain<br><em>petit rituel.</em>',nav:'La carte · Le lieu',action:'Découvrir le menu',side:'L’ambiance commence<br>avant le premier café.',description:'Votre lieu, vos spécialités et toutes les infos pour venir. Aussi agréable à découvrir que votre café.',features:['Carte & menu QR','Photos & ambiance','Adresse & horaires'],utilities:['Un menu à portée de main','Votre adresse, sans chercher','Vos horaires, en un regard']},
 restaurant:{name:'DAR EL GOÛT',image:'restaurant',alt:'Restaurant et cuisine méditerranéenne, photo de concept',eyebrow:'RESTAURANT · CONCEPT DE DÉMONSTRATION',title:'Le goût des<br><em>bons moments.</em>',nav:'Notre table · La carte',action:'Découvrir la carte',side:'On mange aussi<br>avec les yeux.',description:'Vos plats à l’honneur. Votre carte toujours accessible. Et une envie simple : réserver une table.',features:['Carte & plats signature','Demande de réservation','Menu QR & itinéraire'],utilities:['Une carte qui donne envie','Une demande de réservation','Un itinéraire facile']},
 salon:{name:'ATELIER 01',image:'salon',alt:'Barbier réalisant une coupe, photo de concept',eyebrow:'SALON / BARBIER · CONCEPT DE DÉMONSTRATION',title:'Votre style.<br><em>Notre signature.</em>',nav:'Nos services · Rendez-vous',action:'Choisir un rendez-vous',side:'Une belle coupe.<br>Une belle première impression.',description:'Vos prestations, vos réalisations et une prise de contact simple. Vos clients savent à qui confier leur style.',features:['Services & prestations','Galerie de réalisations','Demande de rendez-vous'],utilities:['Vos prestations en un regard','Une galerie qui inspire','Un rendez-vous à demander']},
 shop:{name:'L’ÉDIT',image:'shop',alt:'Intérieur de boutique de vêtements, photo de concept',eyebrow:'BOUTIQUE · CONCEPT DE DÉMONSTRATION',title:'Les belles choses.<br><em>Bien choisies.</em>',nav:'La collection · Notre boutique',action:'Explorer la collection',side:'Votre collection mérite<br>sa propre vitrine.',description:'Vos nouveautés, vos pièces préférées et l’adresse de votre boutique. Donnez envie de passer les voir.',features:['Catalogue & collections','Photos de vos produits','Disponibilité & contact'],utilities:['Vos produits mis en valeur','Des collections à explorer','Une demande en un clic']},
 gym:{name:'MOUVEMENT',image:'gym',alt:'Salle de sport équipée, photo de concept',eyebrow:'SPORT · CONCEPT DE DÉMONSTRATION',title:'Le prochain pas.<br><em>C’est le vôtre.</em>',nav:'Le club · Les séances',action:'Demander une séance',side:'L’envie de commencer.<br>Avant même d’entrer.',description:'Votre salle, vos cours et vos coachs. Montrez l’énergie du lieu et facilitez le premier contact.',features:['Cours & planning','Photos du club','Demande de séance'],utilities:['Vos cours faciles à découvrir','Votre salle en images','Un premier contact facile']},
 other:{name:'VOTRE MAISON',image:'shop',alt:'Espace commercial, photo d’inspiration',eyebrow:'VOTRE ACTIVITÉ · CONCEPT DE DÉMONSTRATION',title:'Votre savoir-faire.<br><em>À découvrir.</em>',nav:'Nos services · Contact',action:'Imaginer mon site',side:'Votre métier a<br>quelque chose à montrer.',description:'Pâtisserie, entreprise locale ou service de quartier : une présence pensée autour de ce que vos clients cherchent.',features:['Vos services & savoir-faire','Galerie & présentation','Contact & localisation'],utilities:['Votre offre enfin claire','Votre identité mise en valeur','Vos clients vous trouvent']}
};
let activeBusiness='cafe';
function updateName(){const entered=$('#business-name').value.trim();const name=entered||businesses[activeBusiness].name;$('#concept-name').textContent=name;$('#concept-contact').textContent=`Créons ${entered?'votre site':'le vôtre'} ↗`;const body=`Bonjour Melek, j’ai vu votre portfolio et j’aimerais discuter d’un site pour ${entered||'mon commerce'}. Mon activité : ${activeBusiness==='salon'?'salon / barbier':activeBusiness==='shop'?'boutique':activeBusiness==='gym'?'sport':activeBusiness==='restaurant'?'restaurant':activeBusiness==='other'?'à préciser':'café'}.`;$('#email-contact').href=`mailto:moalla.melek09@gmail.com?subject=${encodeURIComponent('Un site pour '+(entered||'mon commerce'))}&body=${encodeURIComponent(body)}`;}
function selectBusiness(key){activeBusiness=key;const b=businesses[key];document.querySelectorAll('[data-business]').forEach(el=>{const active=el.dataset.business===key;el.setAttribute('aria-selected',String(active));el.tabIndex=active?0:-1;});$('#concept-image').src=`/assets/${b.image}.webp`;$('#concept-image').alt=b.alt;$('#concept-eyebrow').textContent=b.eyebrow;$('#concept-title').innerHTML=b.title;$('#concept-nav-text').textContent=b.nav;$('#concept-action').innerHTML=`${b.action} <span>↗</span>`;$('#concept-side-title').innerHTML=b.side;$('#concept-description').textContent=b.description;$('#concept-features').replaceChildren(...b.features.map(text=>{const el=document.createElement('span');el.textContent=text;return el;}));['one','two','three'].forEach((key,i)=>$('#utility-'+key).textContent=b.utilities[i]);$('#concept-preview')?.setAttribute('data-type',key);updateName();}
document.querySelectorAll('[data-business]').forEach((button,i,buttons)=>{button.addEventListener('click',()=>selectBusiness(button.dataset.business));button.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();let next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;selectBusiness(buttons[next].dataset.business);buttons[next].focus();}});});
$('#business-name').addEventListener('input',updateName);
const dialog=$('#demo-dialog');
function openBooking(kind){let title=kind==='gym'?'Votre prochaine séance.':'Votre prochain rendez-vous.';$('#dialog-content').innerHTML=`<div class="dialog-inner"><span class="tag">DÉMONSTRATION INTERACTIVE · AUCUNE DEMANDE ENVOYÉE</span><h2>${title}</h2><p id="booking-brand"></p><form id="booking-form"><label>${kind==='gym'?'Votre séance':'Votre prestation'}<select name="service" required>${(kind==='gym'?['Découverte du club','Séance de coaching','Cours collectif']:['Coupe & coiffage','Coupe & barbe','Soin & mise en beauté']).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Le jour qui vous convient<input type="date" name="date" required></label><label>Le créneau souhaité<select name="slot"><option>10:00</option><option>11:30</option><option>14:00</option><option>16:30</option></select></label><button class="button dark" type="submit">Tester la demande <span>↗</span></button></form><div id="booking-result" role="status"></div><p class="demo-notice">Ceci montre le parcours de votre client. Aucun rendez-vous réel n’est créé et aucune donnée n’est envoyée.</p></div>`;$('#booking-brand').textContent=$('#concept-name').textContent;const date=$('#booking-form input[type=date]');const today=new Date();date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const result=$('#booking-result');result.className='booking-confirm';result.textContent=`Démo réussie : ${data.get('service')}, le ${new Date(data.get('date')+'T12:00:00').toLocaleDateString('fr-TN')} à ${data.get('slot')}. Sur votre site, cette demande pourrait vous être transmise pour confirmation.`;});dialog.showModal();}
function openCatalog(){$('#dialog-content').innerHTML=`<div class="dialog-inner"><span class="tag">CATALOGUE FICTIF · DÉMONSTRATION</span><h2>Vos pièces.<br><em>Leur prochain coup de cœur.</em></h2><p id="catalog-brand"></p><div class="catalog-grid"><article class="catalog-product"><img src="/assets/bag.webp" alt="Sac illustrant un catalogue fictif" width="600" height="600"><h3>Le sac signature</h3><p>Collection essentielle · Prix sur demande</p><button data-product="Le sac signature">Se renseigner ↗</button></article><article class="catalog-product"><img src="/assets/knit.webp" alt="Maille illustrant un catalogue fictif" width="600" height="600"><h3>La maille douce</h3><p>Collection essentielle · Prix sur demande</p><button data-product="La maille douce">Se renseigner ↗</button></article></div><div id="catalog-result" role="status"></div><p class="demo-notice">Exemple de catalogue. Ces produits ne sont pas à vendre. Sur votre site, vos clients pourraient demander une disponibilité par message.</p></div>`;$('#catalog-brand').textContent=$('#concept-name').textContent;document.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>{$('#catalog-result').className='booking-confirm';$('#catalog-result').textContent=`« Bonjour, je suis intéressé(e) par ${button.dataset.product.toLowerCase()}. Est-ce disponible ? » — voilà le message que votre client pourrait vous envoyer.`;}));dialog.showModal();}
$('#concept-action').addEventListener('click',()=>{if(['cafe','restaurant'].includes(activeBusiness)){const name=$('#business-name').value.trim();location.href='/menu'+(name?'?business='+encodeURIComponent(name):'');}else if(['salon','gym'].includes(activeBusiness)){openBooking(activeBusiness);}else if(activeBusiness==='shop'){openCatalog();}else{location.hash='contact';}});
$('#dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('#transform-range').addEventListener('input',e=>{const left=100-Number(e.target.value);$('#after-state').style.clipPath=`inset(0 0 0 ${left}%)`;$('#slider-divider').style.left=`${left}%`;});
function showcase(enabled){document.body.classList.toggle('showcase-active',enabled);$('#showcase-bar').hidden=!enabled;$('#showcase-toggle').setAttribute('aria-pressed',String(enabled));const url=new URL(location.href);if(enabled)url.searchParams.set('showcase','1');else url.searchParams.delete('showcase');history.replaceState(null,'',url);if(enabled)location.hash='top';}
$('#showcase-toggle').addEventListener('click',()=>showcase(true));$('#showcase-close').addEventListener('click',()=>showcase(false));if(new URLSearchParams(location.search).has('showcase'))showcase(true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('showcase-active'))showcase(false);});
$('#year').textContent=new Date().getFullYear();
for (const [videoId, toggleId] of [['overdozz-video','preview-pause'],['cookiez-video','cookiez-preview-pause']]) {
 const previewVideo=document.getElementById(videoId), previewToggle=document.getElementById(toggleId);
 if(!previewVideo || !previewToggle) continue;
 let manualPause=false;
 const allowAuto=!matchMedia('(prefers-reduced-motion: reduce)').matches&&!navigator.connection?.saveData;
 function playPreview(){if(!previewVideo.src)previewVideo.src=previewVideo.dataset.src;previewVideo.play().catch(()=>{previewToggle.textContent='Lancer l’aperçu ↗';});}
 previewVideo.addEventListener('play',()=>{previewToggle.textContent='Pause aperçu Ⅱ';previewToggle.setAttribute('aria-pressed','true');});
 previewVideo.addEventListener('pause',()=>{previewToggle.textContent='Lancer l’aperçu ↗';previewToggle.setAttribute('aria-pressed','false');});
 previewVideo.addEventListener('error',()=>{previewToggle.textContent='Aperçu indisponible';previewToggle.disabled=true;});
 previewToggle.addEventListener('click',()=>{if(previewVideo.paused){manualPause=false;playPreview();}else{manualPause=true;previewVideo.pause();}});
 if('IntersectionObserver' in window)new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&allowAuto&&!manualPause)playPreview();else if(!entry.isIntersecting)previewVideo.pause();}},{threshold:.2}).observe(previewVideo);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)previewVideo.pause();});
}

// Scroll reveal: content stays visible unless this runs successfully. Anything already on screen is shown immediately (no flash).
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const revealer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('is-visible');revealer.unobserve(entry.target);}}},{threshold:.12,rootMargin:'0px 0px -6% 0px'});document.querySelectorAll('[data-reveal]').forEach(el=>{if(el.getBoundingClientRect().top<innerHeight)el.classList.add('is-visible');else revealer.observe(el);});document.documentElement.classList.add('reveal-ready');}
