const products=[
{category:'brunch',name:'Le brunch maison',ar:'فطور الدار',description:'Tartine, œufs, viennoiserie & café. Le bon départ.',arDescription:'تارتين، عظم، كرواسون وقهوة. بداية نهار بنينة.',price:24,image:'cafe',allergens:'Œufs · Gluten · Lait',arAllergens:'عظم · غلوتين · حليب',featured:true},
{category:'coffee',name:'Le cappuccino',ar:'كابتشينو',description:'Un espresso, du lait velouté et une mousse délicate.',arDescription:'إسبريسو وحليب برغوة خفيفة.',price:7,image:'coffee',allergens:'Lait',arAllergens:'حليب'},
{category:'coffee',name:'L’espresso',ar:'إسبريسو',description:'Court, intense. Le petit rituel.',arDescription:'قهوة قصيرة وقويّة، للبنة كل يوم.',price:4,image:'coffee',allergens:'Sans lait',arAllergens:'بلا حليب'},
{category:'sweet',name:'La crêpe gourmande',ar:'كريب بالشوكولاتة',description:'Chocolat, fraises & noisettes. Pour le plaisir.',arDescription:'شوكولاتة، فراز وبندق. للمتعة.',price:16,image:'crepe',allergens:'Gluten · Lait · Œufs · Fruits à coque',arAllergens:'غلوتين · حليب · عظم · مكسرات'},
{category:'sweet',name:'Le croissant du matin',ar:'كرواسون الصباح',description:'Doré, feuilleté, tout simplement.',arDescription:'ذهبي ومقرمش، على كيفك.',price:5,image:'pastry',allergens:'Gluten · Lait',arAllergens:'غلوتين · حليب',available:false},
{category:'fresh',name:'L’orange pressée',ar:'عصير برتقال',description:'Fraîche, pressée et pleine de soleil.',arDescription:'طازج ومنعش، كيف شمس الصباح.',price:8,image:'juice',allergens:'Sans lait',arAllergens:'بلا حليب'}
];
let language='fr',category='all';
const businessName=new URLSearchParams(location.search).get('business')?.trim().slice(0,32);if(businessName){document.querySelector('.menu-brand>strong').textContent=businessName;document.title=businessName+' — Menu de démonstration | Melek Moalla';}
const items=document.querySelector('#menu-items');
function render(){let filtered=products.filter(p=>category==='all'||p.category===category);items.replaceChildren(...filtered.map(p=>{const article=document.createElement('article');article.className='menu-product';article.innerHTML=`<img src="/assets/${p.image}.webp" alt="${language==='ar'?p.ar:p.name} — ${language==='ar'?'صورة توضيحية':'photo d’illustration'}" width="900" height="600" loading="lazy">${p.featured?`<span class="menu-feature">${language==='ar'?'اقتراح الدار':'LA SUGGESTION MAISON'}</span>`:''}<div class="menu-product-top"><h2>${language==='ar'?p.ar:p.name}</h2><span class="menu-product-price">${p.price} ${language==='ar'?'د.ت':'DT'}</span></div><p>${language==='ar'?p.arDescription:p.description}</p><div class="menu-product-meta"><span class="${p.available===false?'unavailable':''}">${p.available===false?(language==='ar'?'موش متوفّر اليوم':'Épuisé aujourd’hui'):(language==='ar'?'متوفّر':'Disponible')}</span><span>${language==='ar'?p.arAllergens:p.allergens}</span></div>`;return article;}));document.querySelector('#menu-announcement').textContent=language==='ar'?`${filtered.length} اقتراحات`:`${filtered.length} propositions affichées`;}
document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{category=button.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();}));
document.querySelector('#menu-language').addEventListener('click',()=>{language=language==='fr'?'ar':'fr';document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.querySelectorAll('[data-fr]').forEach(el=>el.innerHTML=el.dataset[language]);const toggle=document.querySelector('#menu-language');toggle.textContent=language==='ar'?'Français':'العربية';toggle.lang=language==='ar'?'fr':'ar';toggle.setAttribute('aria-label',language==='ar'?'عرض القائمة بالفرنسية':'Afficher le menu en arabe');render();});
render();
